dentaldecor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('shoppingbag/', include('shoppingbag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('review/', include('reviews.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('contactus/', include('contactus.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        "addreview/<int:product_id>/",
        views.add_review,
        name="add_review",
    ),
    path(
        'edit_review/<int:review_id>/',
        views.edit_review,
        name='edit_review'),
    path(
        'delete_review/<int:review_id>/',
        views.delete_review,
        name='delete_review'),
]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django.core.validators import MaxLengthValidator


class Review(models.Model):
    """
    Model for creating a User Review
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    created_on = models.DateTimeField(
        auto_now_add=True,
        null=True,
    )
    Rating = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    )

    product_rating = models.IntegerField(choices=Rating, default=0)

    comment_text = models.TextField(
        null=True,
        blank=True,
        validators=[MaxLengthValidator(500)],
    )

    class Meta:
        """
        Order by when review was created on
        """
        ordering = ["-created_on"]

    def __str__(self):
        """
        Returns the username and the Product name as a string
        representation of the object.
        """
        return f"{self.user.username}'s review of {self.product.name}"

reviews/forms.py
from django import forms
from reviews.models import Review
from django.forms import HiddenInput


class RatingForm(forms.ModelForm):
    """
    Form to edit and delete reviews
    """
    class Meta:
        """
        Define model,  form fields, widgets, labels and help texts.
        """
        model = Review
        fields = [
            'product_rating',
            'comment_text',
            ]
        widgets = {
            'product_rating': HiddenInput(),
            'comment_text': forms.Textarea(
                attrs={'placeholder': 'Type in a review here...',
                       'class': 'responsive-textarea',
                       }
            ),
        }
        labels = {
            'product_rating': 'Product Rating',
            'comment_text': 'Review Comment',
        }
        help_texts = {
            'comment_text': 'Maximum 500 characters',
        }

reviews/views.py
from django.shortcuts import render
from .forms import RatingForm
from .models import Review
from products.models import Product
from django.contrib.auth.models import User
from django.shortcuts import (render, get_object_or_404,
                              redirect, reverse)
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required
def add_review(request, product_id):
    """
        Function to add reviews
    """
    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)

    user_review = reviews.filter(user=request.user).exists()

    if user_review:
        messages.error(
            request,
            "You have already submitted a review for this product."
        )
        return redirect('product_detail', product_id=product.id)

    if request.method == 'POST':
        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            review = rating_form.save(commit=False)
            review.user = request.user
            review.product = product
            review.save()
            messages.success(
                request,
                f"Your review for {product.name} has been submitted."
            )
            return redirect('product_detail', product_id=product.id)
        else:
            messages.error(
                request,
                "Error submitting the review. Please check the form."
            )

    else:
        rating_form = RatingForm()

    context = {
        'product': product,
        'reviews': reviews,
        'rating_form': rating_form,
    }
    return render(request, 'reviews/review.html', context)


@login_required
def edit_review(request, review_id):
    """
        Function to edit reviews
    """
    review = get_object_or_404(Review, id=review_id)
    product = review.product
    reviews = Review.objects.filter(product=product)

    if request.method == 'POST':
        rating_form = RatingForm(request.POST, instance=review)
        if rating_form.is_valid():
            product_rating = rating_form.save(commit=False)
            product_rating.save()
            messages.success(request, "Review updated successfully.")
            return redirect('product_detail', product_id=product.id)
        else:
            messages.error(
                request,
                "Error updating the review. Please check the form."
            )
    else:
        rating_form = RatingForm(instance=review)

    user_reviewed = False
    if request.user.is_authenticated:
        user_review = Review.objects.filter(
            product=product, user=request.user
        )
        if user_review.exists():
            user_reviewed = True

    context = {
        'product': product,
        'rating_form': rating_form,
        'reviews': reviews,
        "user_reviewed": user_reviewed,
    }

    return render(request, 'reviews/review.html', context)


@login_required()
def delete_review(request,  review_id):
    """
    This function handles deleting of review for a particular product.
    """
    user = request.user
    review = get_object_or_404(Review, id=review_id)
    product = review.product
    review.delete()
    if user.is_superuser:
        messages.success(
            request,
            f"{review.user}'s review for {product.name} has been deleted "
        )
    else:
        messages.success(
            request,
            f"Your review for {product.name} has been deleted {user.username}"
        )

    return redirect('product_detail', product_id=product.id)

reviews/templates/reviews/delete_review_modal.html
{% if reviews %}
{% for review in reviews %}
<div class="modal fade" id="deleteReviewModal{{ review.id }}" tabindex="-1" aria-labelledby="deleteReviewModalLabel{{ review.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteReviewModalLabel{{ review.id }}">Delete Review</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% if user.is_superuser and user != review.user %}
                    <span class="text-capitalize">{{ request.user }}</span>, Are you sure you want to delete {{ review.user}}'s review and ratings?
                {% else %}
                    <span class="text-capitalize">{{ review.user }}</span>, Are you sure you want to delete your review and ratings?
                {% endif %}
                <form method="post" action="{% url 'delete_review' review.id %}" id="deleteReviewForm">
                    {% csrf_token %}
                    <input type="hidden" name="review_id" id="deleteReviewId">
                    <button type="submit" class="btn btn-danger">Delete Review</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

reviews/templates/reviews/review.html
{% extends 'products/product_detail.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock %}


{% block additional_content %}


<div class="modal fade" id="addReviewModal" tabindex="-1" aria-labelledby="addReviewModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                {% if user_reviewed == True %}
                <div class="modal-header">
                    <h2 class="modal-title " id="addReviewModalLabel">Edit Review</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                {% else %}
                <div class="modal-header">
                    <h2 class="modal-title " id="addReviewModalLabel">Add a Review</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div> 
                {% endif %}
                
                <div class="modal-body"> 
                    <form method="post"  class="reviewform" enctype="multipart/form-data">
                        
                        {% csrf_token %}
                        <div class="card shadow p-1 bg-body-tertiary rounded mb-3">
                            <div class="card-body">
                                
                                <h3 class=" fw-bold text-center">{{ product.name }}</h3>
                                <p class="text-center"> Rate the product out of 5 stars!</p>
                                <div class="rating product_rating text-center">{{rating_form.product_rating}}

                                    <h4 >Product Rating</h4>
                                    <a class="btn"><i class="bi bi-star-fill" id="product_rating-first"></i></a>
                                    <a class="btn"><i class="bi bi-star-fill" id="product_rating-second"></i></a>
                                    <a class="btn"><i class="bi bi-star-fill" id="product_rating-third"></i></a>
                                    <a class="btn"><i class="bi bi-star-fill" id="product_rating-fourth"></i></a>
                                    <a class="btn"><i class="bi bi-star-fill" id="product_rating-fifth"></i></a>
                                </div>


                            </div>

                            <!-- Comment Box -->

                            <div class="card-body">
                                <h4 class="text-center">Leave a Review!</h4>
                                <div class="form-group ">
                                    <label for="id_comment_text" class="visually-hidden">Review:</label>
                                    {{ rating_form.comment_text }}

                                </div>
                                <small class="form-text text-muted">{{ rating_form.comment_text.help_text }}</small>
                            </div>
                            {% if user_reviewed == True %}
                            <button type="submit" class="btn btn-success">Update Review</button>
                            {% else %}
                            <button type="submit" class="btn btn-success">Submit Review</button>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </div>

</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'products/js/add_rating.js' %}">
    </script>
    
    {% include 'products/includes/quantity_input_script.html' %}
    <script>
        $(document).ready(function () {
    
            $('#addReviewModal').modal('show');
    
        });
        
    </script>
{% endblock %}