dentaldecor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('shoppingbag/', include('shoppingbag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('review/', include('reviews.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('contactus/', include('contactus.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
]

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    '''
        Order model
    '''
    order_number = models.CharField(max_length=32, null=False,
                                    editable=False)
    user_profile = models.ForeignKey(UserProfile,
                                     on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False,
                                 blank=False)
    email = models.EmailField(max_length=254, null=False,
                              blank=False)
    phone_number = models.CharField(max_length=20, null=False,
                                    blank=False)
    country = CountryField(blank_label='Country *', null=False,
                           blank=False)
    postcode = models.CharField(max_length=20, null=True,
                                blank=True)
    town_or_city = models.CharField(max_length=40, null=False,
                                    blank=False)
    street_address1 = models.CharField(max_length=80, null=False,
                                       blank=False)
    street_address2 = models.CharField(max_length=80, null=True,
                                       blank=True)
    county = models.CharField(max_length=80, null=True,
                              blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_shoppingbag = models.TextField(null=False, blank=False,
                                            default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False,
                                  default='')

    def _generate_order_number(self):
        '''
        Generate a random, unique order number using UUID
        '''
        return uuid.uuid4().hex.upper()

    def update_total(self):
        ''' Update the total every time an item is added'''
        self.order_total = (
         self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum']
         or 0
        )
        self.grand_total = self.order_total
        self.save()

    def save(self, *args, **kwargs):
        '''
        Override the original save method to set the order number
        if it hasn't been set already.
        '''
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=20, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU No:{self.product.sku} on order {self.order.order_number}'

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Wishlist(models.Model):
    """
    wishlist model
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.product.name} in {self.product.category}'

wishlist/views.py
from django.shortcuts import (render, get_object_or_404,
                              HttpResponseRedirect, redirect,
                              reverse, HttpResponse)
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Wishlist
from products.models import Product
from django.contrib import messages


@login_required
def wishlist(request):
    """
        Renders wishlist page
    """
    wish_items = Wishlist.objects.filter(user=request.user)
    context = {
        'wish_items': wish_items,
    }

    return render(request, 'wishlist/wishlist.html', context)


@login_required
def add_to_wishlist(request, product_id):
    """
        Handles Adding items to wishlist
    """
    product = get_object_or_404(Product, id=product_id)
    try:
        wish_item = Wishlist.objects.get(user=request.user,
                                         product=product)
        messages.info(request, f'{product.name} is already in \
                      your wishlist.')
    except Wishlist.DoesNotExist:
        Wishlist.objects.create(user=request.user, product=product)
        messages.success(
            request, f'{product.name} added  to wishlist'
        )

    return redirect('product_detail', product_id=product.id)


def remove_from_wishlist(request, product_id):
    """
        Handles removing items from wishlist
    """
    product = get_object_or_404(Product, id=product_id)
    print(product)
    wish_item = Wishlist.objects.get(user=request.user, product=product)
    print(wish_item)

    if request.method == 'POST':
        wish_item.delete()
        messages.success(
            request, f'{product.name} removed from your wishlist.'
        )

    return redirect('wishlist')

wishlist/templates/wishlist/remove_item_modal.html
<div class="modal fade" id="removeModal{{ item.product.id }}" tabindex="-1" aria-labelledby="removeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeModalLabel">Confirm Removal</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to remove {{ item.product.name }} from your wishlist?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form method="post" action="{% url 'remove_from_wishlist' item.product.id %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            </div>
        </div>
    </div>
</div>

wishlist/templates/wishlist/wishlist.html
{% extends "base.html" %}
{% load static %}


{% block extra_title %}
Wishlist
{% endblock extra_title %}

{% block content %}

{% if wish_items %}
<div class="carousal-border container">
    <div class="row  ">
        <h1 class="mt-4 mb-4">Your Wishlist</h1>
        {% for item in wish_items %}
        <h2>{{ forloop.counter }}.</h2>
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2 mb-4 ">
            <div class="card h-100">
                <div class="card-body d-flex align-items-center justify-content-center">
                    <div class="image-container">
                    {% if item.product.image %}
                    <a href="{{ item.product.image.url }}" target="_blank" aria-label="product-image">
                        <img class="card-img-top img-fluid wishlist-image" src="{{ item.product.image.url }}"
                        alt="{{ item.product.name }}">
                    </a>
                    {% else %}
                    <a href="{{ MEDIA_URL }}invalid-image.webp" aria-label="Go up link">
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}invalid-image.webp" alt="{{ item.product.name }}">
                    </a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card h-100 position-relative">
                <div class="card-body">
                    <h3 class="fw-bold mt-2 fs-4">{{ item.product.name }}</h3>
                    <p class="mt-3 fw-bold">{{ item.product.description }}</p>
                    <p class="lead mb-0 text-left fw-bold">€ {{ item.product.price }}</p>
                    <form class="form" action="{% url 'add_to_shoppingbag' item.product.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        <div class="form-row">
                            {% with item.product.has_sizes as s %}
                            {% if s %}
                            <div class="col-12">
                                <label for="id_product_size"><strong>Size:</strong></label>
                                <select class="form-control form-select form-select-sm w-75" name="product_size" id='id_product_size'>
                                    {% if item.product.category.name == 'Wallart' %}
                                    <option value="small">Small 30* 40cm</option>
                                    <option value="medium" selected>Medium 40* 60cm</option>
                                    <option value="large">Large 60* 80cm</option>
                                    {% elif item.product.category.name == 'Educational' %}
                                    <option value="medium" selected>Medium</option>
                                    <option value="large">Large</option>
                                    {% elif item.product.category.name == 'Apparel' %}
                                    <option value="medium" selected>Medium</option>
                                    <option value="large">Large</option>
                                    {% elif item.product.category.name == 'Collectables' %}
                                    <option value="medium" selected>Medium</option>
                                    <option value="large">Large</option>
                                    {% else %}
                                    <option value="medium">Medium</option>
                                    {% endif %}
                                </select>
                            </div>
                            {% endif %}
                            <div class="col-12">
                                <label for="id_qty_{{ item.product.id }}"
                                    class="mt-3"><strong>Quantity:</strong></label>
                                <div class="input-group w-75">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-outline-danger border-0 rounded-circle"
                                            data-item_id="{{ item.product.id }}"
                                            id="decrement-qty_{{ item.product.id }}" aria-label="decrease button">
                                            <span class="icon">
                                                <i class="bi bi-dash-circle"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="99" data-item_id="{{ item.product.id }}"
                                        id="id_qty_{{ item.product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-outline-success border-0 rounded-circle"
                                            data-item_id="{{ item.product.id }}"
                                            id="increment-qty_{{ item.product.id }}" aria-label="increase button">
                                            <span class="icon">
                                                <i class="bi bi-plus-circle"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            {% endwith %}
                            <div class="col-12 mt-2">
                                <div class="d-flex  align-items-center">
                                    
                                    <input type="submit" class="btn dental-decor-actionbtn shopping-bag me-auto text-uppercase" value="Add to Bag">
                                    
                                </div>

                            </div>
                            
                        </div>
                    </form>
                    <div class="col-12 mt-2">
                        <div class="position-absolute top-0 end-0 ">
                            
                            {% include 'wishlist/remove_item_modal.html' %}
                            <button type="button" class="btn text-danger ms-auto rounded-circle " data-bs-toggle="modal"
                                data-bs-target="#removeModal{{ item.product.id }}" aria-label="remove wishlist button">
                                <i class="bi bi-x-circle"></i>
                            </button>
                        </div>

                    </div>

                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-12 text-center"> 
            <a href="{% url 'shop_products' %}" class="btn mb-1  btn-outline-dark rounded-0 me-1 " aria-label="shop page link">
                <span class="icon">
                    <i class="bi bi-caret-left"></i>
                </span>
                <span class="text-uppercase ">Browse</span>
            </a>
        </div>
    </div>
    
    
    <div class="position-fixed bottom-0 end-0 p-3 m-3">
        <a class="btn fw-bold" href="{% url 'wishlist' %}" id="scroll-to-top" aria-label="Go up link">
            <i class="bi bi-arrow-up-circle "></i>
        </a>
    </div>

    {% else %}
    <div class="carousal-border container">
        <h1 class="mt-4 ">Your Wishlist</h1>
    <div class="col-12 mx-auto min-vh-100 d-flex flex-column align-items-center justify-content-center ">
        <h2 class="text-center fw-bold">Your wishlist is empty.</h2>
        <div>
        <a href="{% url 'shop_products' %}" class="btn mb-1  btn-outline-dark rounded-0 me-1" aria-label="shop page link">
            <span class="icon">
                <i class="bi bi-caret-left"></i>
            </span>
            <span class="text-uppercase ">Browse</span>
        </a>
        </div>
    </div>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}


{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}